# Generated by Django 5.2.6 on 2025-09-28 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("is_won", models.BooleanField(default=False)),
                ("is_finished", models.BooleanField(default=False)),
                ("guess1", models.CharField(blank=True, max_length=5, null=True)),
                ("guess2", models.CharField(blank=True, max_length=5, null=True)),
                ("guess3", models.CharField(blank=True, max_length=5, null=True)),
                ("guess4", models.CharField(blank=True, max_length=5, null=True)),
                ("guess5", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word_to_guess",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.word"
                    ),
                ),
            ],
        ),
    ]
